theme: jekyll-theme-leap-day
title: Malaysian Government Official Social Media Channels
description: A list of social media accounts from the Malaysian Government and officers related to the COVID-19 pandemic.
# Google Analytics
google_analytics: UA-161468459-1
